package com.salesbox.message;

/**
 * User: luult
 * Date: 5/8/14
 */
public enum CommonMessage
{
    SUCCESS,
    FAIL,
    NOT_LINKED_GOOGLE,
    NOT_LINKED_OUTLOOK,
    NOT_LINKED_O365,
    NUMBER_LICENCE_NOT_VALID,
    DUPLICATED_MULTI_RELATION,
    RELATION_NOT_FOUND,
    CAN_NOT_DELETE_AN_USING_RELATION,
    SUBSCRIPTION_EXISTED,
    NOT_EXISTED,
    TASK_EXECUTION_IN_BACKGROUND,


    CANNOT_ADD_FOR_MORE_THAN_250_OBJECT,
    CANNOT_ADD_FOR_MORE_THAN_200_OBJECT,
    CANNOT_ADD_FOR_MORE_THAN_100_OBJECT,

    EXISTED;
}
