package com.salesbox.message;

/**
 * Created by: hunglv
 * Date: 10/7/14
 */
public enum ImportExportMessage
{
    DUPLICATED_INPUT_EMAIL,
    EMAIL_INVALID,
    DUPLICATED_LOCAL_EMAIL,
    DUPLICATED_SHARED_EMAIL,
    DATA_MISSING,
    INVALID,
    NOT_FOUND,
    ROW,
    IMPORT_PROSPECT_FAILED,
    PRODUCT_NAME_MUST_UNIQUE,

    ACCOUNT_SHEET_NAME,
    CONTACT_SHEET_NAME,
    PROSPECT_SHEET_NAME,
    ORDER_ROW_SHEET_NAME,
    PRODUCT_SHEET_NAME,

    PRE_EXPORT_FILE_NAME,
    PRE_IMPORT_FILE_NAME,
    PRE_SUBJECT_EXPORT,
    PRE_FAIL_IMPORT_FILE_NAME,

    //Reselling
    RECRUITED_USER_EXISTED,
    RECRUITED_USER_NOT_VALID


}
