package com.salesbox.message;

/**
 * Created by hungnh on 09/07/2014.
 */
public enum LocalizationMessage
{
    USER_NOT_FOUND,
    ASSIGNING_USER_NOT_FOUND,
    ASSIGNED_USER_NOT_FOUND,
    UNASSIGNING_USER_NOT_FOUND,
    UNASSIGNED_USER_NOT_FOUND,
    ADD_ANOTHER_ADMIN_BEFORE_UNASIGNED_ADMIN,
    ENTERPRISE_NOT_MATCH,
    USER_ALREADY_EXIST_AND_BELONG_TO_ANOTHER_COMPANY,
    SUCCESS,
    FAIL,
    NOT_LOGIN,
    TOKEN_EXPIRED_OR_DOESNT_EXIST,
    VERSION_DOES_NOT_SUPPORT,
    LANGUAGE_NOT_FOUND,

    USER_EMAIL_DUPLICATE,
    COMPANY_EMAIL_DUPLICATE,
    COMPANY_NOT_FOUND,

    VALIDATE_EXCEPTION,

    UNIT_NOT_FOUND,
    WORK_DATA_ORGANISATION_NAME_UNIQUE,
    WORK_DATA_ACTIVITY_NAME_UNIQUE,

    PROSPECT_NOT_FOUND,
    NOTE_NOT_FOUND,
    UPLOAD_NOT_FOUND,

    ORDER_ROW_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    LINE_OF_BUSINESS_NOT_FOUND,

    WORK_DATA_NOT_FOUND,
    ACTIVITY_NOT_FOUND,
    CONTACT_NOT_FOUND,
    FOCUS_ERROR,
    LEAD_NOT_FOUND,
    TASK_NOT_FOUND,
    MEASUREMENT_TYPE_NOT_FOUND,
    ORGANISATION_NOT_FOUND,
    ITEMS_MORE_THAN_30,
    ENTERPRISE_NOT_FOUND,
    STORAGE_NOT_UNIQUE,
    STORAGE_NOT_FOUND,

    IMAGE_NOT_FOUND,

    APPOINTMENT_NOT_FOUND,
    APPOINTMENT_DELETED,
    START_DATE_IS_AFTER_END_DATE,
    ACCEPTED_INVITATION,
    DECLINED_INVITATION,
    WORKDATA_ACTIVITY_DELETED,
    CAMPAIGN_NOT_FOUND,
    COMMUNICATION_TYPE_NOT_FOUND,
    DURATION_NOT_FOUND,
    DIAL_TIME_NOT_FOUND,

    ERROR_RESET_BECAUSE_USING,
    ERROR_DELETE_BECAUSE_USING,

    EXISTED_PROSPECT_IN_COMMUNICATION,
    PERMISSION_DENIED,
    USER_NOT_PAYING,

    CANNOT_CHANGE_ORGANISATION_BECAUSE_EXISTING_ACTIVE_TASK,
    CANNOT_CHECK_OFF_STEP_OF_CLOSED_OPPORTUNITY,

    NOT_ALLOW_CHANGE_MEDIAN_DEAL_SIZE,
    NOT_ALLOW_CHANGE_MEDIAN_DEAL_TIME,
    RECRUITED_USER_EXISTED,
    RECRUITED_USER_DUPLICATED,
    RECRUITED_USER_NOT_VALID,
    THE_SALESBOX_CRM_TEAM,

    INVOICE_ITEM_NAME,
    INVOICE_TEMPLATE_FOOTER_LINE_1,
    INVOICE_TEMPLATE_FOOTER_LINE_2,
    MONTH,
    GOOGLE_API_KEY_IS_EXPIRED,
    SUGGESTED_ACCOUNT,
    USER_IS_NOT_FROM_MAESTRANO,

    FOLDER_NOT_FOUND,
    DOCUMENT_NOT_FOUND,
    ENTERPRISE_ALREADY_REACHED_THE_MAXIMUM_LICENSE,
	OWNER_NOT_FOUND,
    CREATE_FORTNOX_INOIVES_ERROR,
    CREATE_FORTNOX_CUSTOMER_ERROR;
}
