package com.salesbox.message;

/**
 * User: luult
 * Date: 5/8/14
 */
public enum UserMessage
{
    USER_EMAIL_NOT_FOUND,
    USERNAME_NOT_FOUND,
    USER_NOT_FOUND,
    INCORRECT_PASSWORD,
    DO_NOT_HAVE_PERMISSION,
    NOT_EXISTING_TOKEN,
    NOT_CHANGE_MAIN_CONTACT,
    EXISTING_EMAIL,
    REACH_LIMIT_LICENSE,
    EXPIRE_TRIAL_TIME,
    YOUR_CARD_CANNOT_PAYMENT_CONTINUE,
    YOUR_USERS_MORE_THAN_PAID_LICENSES,
    NOT_MATCHING_APP_CODE,
    EXPIRED_APP_CODE,
    CANNOT_DEACTIVATE_USER_HAS_ACTIVE_TASK,
    CANNOT_DEACTIVATE_USER_HAS_ACTIVE_PROSPECT,
    CANNOT_DEACTIVATE_USER_HAS_ACTIVE_MEETING,
    INCORRECT_OLD_PASSWORD,
    CAN_NOT_CHANGE_USERNAME,
    CONFIRM_TOKEN_INVALID,
    EXPIRE_CONFIRMATION,
    YOUR_ACCOUNT_HAS_BEEN_CANCELLED,

    NUMBER_LICENSE_LESS_THAN_NUMBER_ACTIVE_CAUSE_BY_CANCEL,
    NUMBER_LICENSE_LESS_THAN_NUMBER_ACTIVE_CAUSE_BY_FAIL,
    REQUIRE_AT_LEAST_ONE_ADMIN,
    COLUMNS_CONFIG_NOT_FOUND
}
